const VOCAB_DATA = {
    "気持ち（ポジティブ）": [
        { ja: "昨日見た映画感動したよ", en: ["The movie I saw yesterday was really moving."], native: ["That movie I watched yesterday hit me right in the feels.", "I saw this movie yesterday and it got me so emotional."], youglish: "I was really moved" },
        { ja: "やっと週末だ、嬉しい", en: ["It's finally the weekend. I'm happy."], native: ["TGIF! I'm so ready for the weekend.", "Finally the weekend. I couldn't be happier."], youglish: "I'm so happy it's the weekend" },
        { ja: "新しい仕事めっちゃ楽しい", en: ["My new job is really fun."], native: ["I'm loving my new job.", "My new gig is awesome. I'm having a blast."], youglish: "I'm really enjoying my job" },
        { ja: "試験受かった！信じられない", en: ["I passed the exam! I can't believe it."], native: ["I passed! No way, I'm freaking out!", "I actually passed! I'm over the moon!"], youglish: "I can't believe I passed" },
        { ja: "久しぶりに会えて嬉しかった", en: ["I was happy to see you after such a long time."], native: ["It was so good to see you again. It's been forever.", "I'm so glad we finally caught up."], youglish: "it was great to see you" },
        { ja: "推しのライブ最高すぎた", en: ["My favorite artist's concert was amazing."], native: ["That concert was insane. I'm still on a high.", "Best concert ever. I'm still buzzing."], youglish: "the concert was amazing" },
        { ja: "朝起きたら雪積もってた、テンション上がった", en: ["When I woke up, there was snow everywhere. I got excited."], native: ["I woke up to snow and I was like a little kid.", "There was snow this morning and it totally made my day."], youglish: "I was so excited when I saw" },
        { ja: "ずっと欲しかったやつやっと買えた", en: ["I was finally able to buy the thing I've been wanting."], native: ["I finally got my hands on it!", "I've been eyeing this forever and I finally snagged it."], youglish: "I finally got it" },
    ],
    "気持ち（ネガティブ）": [
        { ja: "今日の会議だるいな", en: ["I don't want to go to today's meeting."], native: ["Ugh, I'm so not feeling today's meeting.", "I'm dreading today's meeting."], youglish: "I don't want to go to the meeting" },
        { ja: "締め切りやばい、間に合わないかも", en: ["The deadline is tight. I might not make it."], native: ["The deadline's killing me. I don't think I'm gonna make it.", "I'm cutting it super close with this deadline."], youglish: "I might not make the deadline" },
        { ja: "昨日寝れなくてしんどい", en: ["I couldn't sleep last night and I'm exhausted."], native: ["I barely slept last night and I'm wrecked.", "I tossed and turned all night. I'm dead."], youglish: "I couldn't sleep last night" },
        { ja: "あー言わなきゃよかった", en: ["I wish I hadn't said that."], native: ["Ugh, I should've kept my mouth shut.", "I totally put my foot in my mouth."], youglish: "I wish I hadn't said that" },
        { ja: "電車で足踏まれてムカついた", en: ["Someone stepped on my foot on the train and it annoyed me."], native: ["Some dude stepped on my foot on the train. So annoying.", "I got my foot stepped on and I was fuming."], youglish: "it really annoyed me" },
        { ja: "せっかくの休みなのに雨かよ", en: ["It's raining even though it's my day off."], native: ["Of course it rains on my day off.", "Rain on my day off? Seriously?"], youglish: "it's raining on my day off" },
        { ja: "あの映画期待してたのにつまらなかった", en: ["I was looking forward to that movie but it was boring."], native: ["I had high hopes for that movie but it was a total letdown.", "That movie was such a disappointment. What a waste."], youglish: "I was disappointed" },
        { ja: "スマホ落として画面割れた", en: ["I dropped my phone and the screen cracked."], native: ["I cracked my phone screen. I'm so mad at myself.", "I dropped my phone and shattered the screen. Great."], youglish: "I dropped my phone" },
    ],
    "思うこと・考えること": [
        { ja: "明日は雨だと思う", en: ["I think it will rain tomorrow."], native: ["I bet it's gonna rain tomorrow.", "Looks like rain tomorrow."], youglish: "I think it's going to rain" },
        { ja: "転職しようかなって考えてる", en: ["I'm thinking about changing jobs."], native: ["I've been toying with the idea of switching jobs.", "I'm kind of mulling over a career change."], youglish: "I'm thinking about changing jobs" },
        { ja: "あの人怒ってる気がする", en: ["I feel like that person is angry."], native: ["Something tells me they're upset.", "I get the sense they're mad."], youglish: "I feel like they're upset" },
        { ja: "引っ越すかどうか迷ってる", en: ["I can't decide whether to move or not."], native: ["I'm on the fence about moving.", "I keep going back and forth on whether to move."], youglish: "I can't decide whether to" },
        { ja: "自炊した方がいいのは分かってる", en: ["I know I should cook at home more."], native: ["I know I should be cooking more.", "I really need to start cooking for myself."], youglish: "I know I should" },
        { ja: "やっぱり早起きした方が調子いい", en: ["I feel better when I wake up early, as I thought."], native: ["Waking up early really does make a difference.", "I knew it. I'm way more productive when I get up early."], youglish: "I feel better when I wake up early" },
        { ja: "あのとき違う選択してたらどうなってたかな", en: ["I wonder what would have happened if I had chosen differently."], native: ["I sometimes wonder what my life would be like if I'd gone the other way.", "What if I'd made a different call back then?"], youglish: "what would have happened if" },
        { ja: "考えすぎかもしれないけど気になる", en: ["I might be overthinking it, but it bothers me."], native: ["I'm probably reading too much into it, but it bugs me.", "Maybe I'm overthinking this, but I can't let it go."], youglish: "maybe I'm overthinking it" },
    ],
    "ニュアンスを加える": [
        { ja: "一応傘持っていくね", en: ["I'll bring an umbrella just in case."], native: ["I'll grab an umbrella just to be safe.", "Might as well bring an umbrella, just in case."], youglish: "just in case" },
        { ja: "とりあえずコーヒー飲もう", en: ["Let's have some coffee for now."], native: ["Let's just grab a coffee first.", "Coffee first. Everything else can wait."], youglish: "let's get some coffee first" },
        { ja: "ちなみに、あの店もう閉まったらしいよ", en: ["By the way, I heard that shop has closed."], native: ["Oh, just so you know, that place shut down apparently.", "Fun fact: that store actually closed down."], youglish: "by the way" },
        { ja: "やっぱりあのレストラン美味しかった", en: ["That restaurant was good, just as I expected."], native: ["I knew that restaurant would be good. It didn't disappoint.", "Sure enough, that restaurant was amazing."], youglish: "just as I expected" },
        { ja: "なんとなく今日は出かけたくない", en: ["I don't feel like going out today for some reason."], native: ["I just don't feel like going out today. No real reason.", "I can't explain it but I just wanna stay in today."], youglish: "I don't feel like going out" },
        { ja: "せっかくの旅行だし楽しもう", en: ["Since we're on this trip, let's enjoy it."], native: ["We're here, so we might as well make the most of it.", "It'd be a shame not to enjoy this trip."], youglish: "we might as well" },
        { ja: "まあまあだったかな、めちゃくちゃ良くはない", en: ["It was okay, not great though."], native: ["It was decent. Nothing to write home about.", "Eh, it was alright I guess. Not amazing."], youglish: "it was okay but not great" },
        { ja: "結局さ、自分で決めるしかないんだよね", en: ["In the end, you have to decide for yourself."], native: ["At the end of the day, it's your call.", "It all comes down to what you want, you know?"], youglish: "at the end of the day" },
    ],
    "感想を伝える": [
        { ja: "この店のラーメンめっちゃうまい", en: ["The ramen at this place is really good."], native: ["This place has killer ramen.", "Dude, the ramen here is insane."], youglish: "the food here is really good" },
        { ja: "あの映画のラスト、ありえないよね", en: ["The ending of that movie was unbelievable."], native: ["That ending was wild. I did not see that coming.", "The twist at the end? Get out of here!"], youglish: "I did not see that coming" },
        { ja: "この曲聴いてみて、めっちゃいいから", en: ["Listen to this song. It's really good."], native: ["You gotta hear this song. It's a banger.", "Check this song out, it slaps."], youglish: "you should listen to this song" },
        { ja: "昨日のプレゼン上手かったよ", en: ["Your presentation yesterday was good."], native: ["You crushed that presentation yesterday.", "Your presentation was on point."], youglish: "your presentation was great" },
        { ja: "この前行ったカフェすごくよかった", en: ["The cafe I went to the other day was really nice."], native: ["I checked out this cafe the other day and it was amazing.", "I found this awesome cafe recently."], youglish: "I found this great place" },
        { ja: "あの新作ゲーム、期待はずれだった", en: ["That new game was disappointing."], native: ["That new game was a total letdown.", "I was so hyped for that game but it flopped."], youglish: "it was a disappointment" },
        { ja: "この本おすすめ、人生変わるレベル", en: ["I recommend this book. It's life-changing."], native: ["You need to read this book. It's a game changer.", "This book blew my mind. Seriously, read it."], youglish: "you should read this book" },
        { ja: "あの人の歌、生で聴くと鳥肌立つ", en: ["When you hear that person sing live, you get goosebumps."], native: ["Their voice live gives me chills every time.", "Hearing them perform in person hits different."], youglish: "it gives me goosebumps" },
    ],
    "相槌": [
        { ja: "へえ、そうなんだ", en: ["Oh, is that so?", "I see."], native: ["Oh really? Huh.", "No kidding."], youglish: "oh really" },
        { ja: "確かにね", en: ["That's true.", "You're right."], native: ["Good point.", "Fair enough.", "Can't argue with that."], youglish: "that's a good point" },
        { ja: "わかる、それな", en: ["I understand. I agree."], native: ["I feel that.", "Same here.", "Big mood."], youglish: "I know what you mean" },
        { ja: "まじで？それはやばいね", en: ["Really? That's crazy."], native: ["No way! That's wild.", "Shut up, are you serious?"], youglish: "are you serious" },
        { ja: "え、うそでしょ", en: ["What? You're kidding."], native: ["Wait, what? No way!", "Get outta here. You're joking."], youglish: "you're kidding" },
        { ja: "それは大変だったね", en: ["That must have been tough."], native: ["That sounds rough.", "Oh man, that's brutal. I'm sorry."], youglish: "that must have been tough" },
        { ja: "いいなー、うらやましい", en: ["That's nice. I'm jealous."], native: ["Lucky you! I wish that were me.", "Okay, I'm lowkey jealous."], youglish: "I'm so jealous" },
        { ja: "うんうん、で、どうなったの？", en: ["Yeah, yeah. So what happened next?"], native: ["Uh-huh, uh-huh. And then what?", "Go on, go on. What happened?"], youglish: "and then what happened" },
    ],
    "相手の話を深堀する質問": [
        { ja: "それってどういうこと？", en: ["What do you mean by that?"], native: ["Wait, what do you mean?", "Can you break that down for me?"], youglish: "what do you mean by that" },
        { ja: "きっかけは何だったの？", en: ["What made you start?", "What was the reason?"], native: ["What got you into that?", "How did that come about?"], youglish: "what made you decide to" },
        { ja: "それで結局どうなったの？", en: ["So what happened in the end?"], native: ["So how did it all play out?", "And? What was the outcome?"], youglish: "what happened in the end" },
        { ja: "他の人はなんて言ってた？", en: ["What did other people say?"], native: ["What did everyone else think?", "How did other people react?"], youglish: "what did other people think" },
        { ja: "一番大変だったのはどこ？", en: ["What was the hardest part?"], native: ["What was the toughest part of it?", "Where did you struggle the most?"], youglish: "what was the hardest part" },
        { ja: "もしやり直せるとしたらどうする？", en: ["If you could do it over, what would you do?"], native: ["If you had a do-over, what would you change?", "Knowing what you know now, would you do it differently?"], youglish: "if you could do it again" },
        { ja: "それって前からそうだったの？", en: ["Has it always been like that?"], native: ["Has it been that way for a while?", "Was it always like that or is this new?"], youglish: "has it always been like that" },
        { ja: "具体的にはどんな感じ？", en: ["What's it like specifically?"], native: ["Can you paint me a picture?", "What does that actually look like?"], youglish: "what is it like" },
    ],
    "話の切り出し": [
        { ja: "そういえば、聞いた？", en: ["By the way, did you hear?"], native: ["Oh, did you hear about this?", "Hey, guess what?"], youglish: "did you hear about" },
        { ja: "ねえ、ちょっと相談したいことあるんだけど", en: ["Hey, there's something I want to talk to you about."], native: ["Hey, can I run something by you?", "So, I need your advice on something."], youglish: "I need your advice on something" },
        { ja: "面白い話があるんだけど聞いてくれる？", en: ["I have a funny story. Will you listen?"], native: ["Okay so get this.", "You're not gonna believe what happened."], youglish: "you're not going to believe this" },
        { ja: "前から気になってたんだけど", en: ["I've been wondering about this for a while."], native: ["I've been meaning to ask you this.", "So this has been bugging me for a while."], youglish: "I've been meaning to ask you" },
        { ja: "話変わるんだけどさ", en: ["I'm changing the subject, but..."], native: ["Random, but...", "Totally off topic, but..."], youglish: "by the way" },
        { ja: "実はさ、言おうか迷ってたんだけど", en: ["Actually, I was wondering whether to tell you or not."], native: ["So, I've been debating whether to say this...", "Okay, don't judge me, but..."], youglish: "I wasn't sure if I should tell you" },
        { ja: "最近気づいたんだけど", en: ["I noticed recently that..."], native: ["So I just realized something.", "It just hit me the other day."], youglish: "I just realized something" },
        { ja: "これ言うと引くかもしれないけど", en: ["You might be put off by this, but..."], native: ["Don't laugh, but...", "This might sound weird, but..."], youglish: "this might sound weird but" },
    ],
};
