const VOCAB_DATA = {
    "気持ち（ポジティブ）": [
        { ja: "いいね", en: ["That's nice.", "That's cool.", "Sounds good."], native: ["That's awesome!", "Love it!", "I'm all for it!"] },
        { ja: "嬉しい", en: ["I'm happy.", "I'm glad."], native: ["I'm thrilled!", "That made my day!", "I'm over the moon!"] },
        { ja: "楽しい", en: ["It's fun.", "I'm having fun."], native: ["I'm having a blast!", "This is a good time!", "I'm loving it!"] },
        { ja: "やったー", en: ["I did it!", "Yes!"], native: ["Nailed it!", "Let's go!", "Woohoo!"] },
        { ja: "ワクワクする", en: ["I'm excited.", "I can't wait."], native: ["I'm pumped!", "I'm stoked!", "I'm so hyped!"] },
        { ja: "安心した", en: ["I'm relieved.", "I feel safe now."], native: ["What a relief!", "That's a load off my mind!", "I can breathe again."] },
        { ja: "感動した", en: ["I'm moved.", "I was impressed."], native: ["That hit me right in the feels.", "That was so touching!", "I got chills."] },
        { ja: "最高", en: ["It's the best.", "It's great."], native: ["It's top-notch!", "It doesn't get better than this!", "This is fire!"] },
    ],
    "気持ち（ネガティブ）": [
        { ja: "疲れた", en: ["I'm tired.", "I'm exhausted."], native: ["I'm beat.", "I'm wiped out.", "I'm running on empty."] },
        { ja: "めんどくさい", en: ["It's annoying.", "I don't want to do it."], native: ["What a hassle.", "I can't be bothered.", "Ugh, so tedious."] },
        { ja: "ムカつく", en: ["I'm angry.", "It makes me mad."], native: ["That ticks me off.", "That's so annoying!", "I'm fuming."] },
        { ja: "悲しい", en: ["I'm sad.", "I feel down."], native: ["I'm bummed.", "That's a bummer.", "I'm feeling blue."] },
        { ja: "不安", en: ["I'm worried.", "I'm anxious."], native: ["I've got butterflies.", "It's eating me up.", "I'm on edge."] },
        { ja: "つまらない", en: ["It's boring.", "I'm bored."], native: ["This is a snooze.", "I'm bored out of my mind.", "What a drag."] },
        { ja: "がっかり", en: ["I'm disappointed.", "That's too bad."], native: ["What a letdown.", "That's a bummer.", "I had my hopes up."] },
        { ja: "恥ずかしい", en: ["I'm embarrassed.", "I feel shy."], native: ["I wanted to crawl into a hole.", "That was so cringe.", "I'm mortified."] },
    ],
    "思うこと・考えること": [
        { ja: "〜だと思う", en: ["I think ~.", "I believe ~."], native: ["I'd say ~.", "I feel like ~.", "If you ask me, ~."] },
        { ja: "たぶん", en: ["Maybe.", "Probably."], native: ["I guess so.", "More likely than not.", "Chances are ~."] },
        { ja: "〜な気がする", en: ["I feel like ~.", "I have a feeling ~."], native: ["Something tells me ~.", "I get the sense that ~.", "My gut says ~."] },
        { ja: "迷ってる", en: ["I can't decide.", "I'm not sure."], native: ["I'm torn.", "I'm on the fence.", "I'm going back and forth."] },
        { ja: "なるほど", en: ["I see.", "I understand."], native: ["That makes sense.", "Gotcha.", "Fair point."] },
        { ja: "そういうことか", en: ["So that's what it means.", "Now I understand."], native: ["Oh, that's what it is!", "It all clicks now.", "That explains it."] },
        { ja: "確かに", en: ["That's true.", "You're right."], native: ["Good point.", "Can't argue with that.", "Fair enough."] },
        { ja: "微妙", en: ["It's not great.", "I'm not sure about it."], native: ["It's kind of meh.", "It's iffy.", "I could go either way."] },
    ],
    "ニュアンスを加える": [
        { ja: "一応", en: ["Just in case.", "For now."], native: ["Just to be safe.", "As a precaution.", "I'll go ahead and ~, just in case."] },
        { ja: "とりあえず", en: ["For now.", "First of all."], native: ["Let's just ~ for now.", "For starters.", "As a starting point."] },
        { ja: "ちなみに", en: ["By the way.", "Also."], native: ["Just so you know.", "Fun fact:", "On a side note."] },
        { ja: "やっぱり", en: ["As I thought.", "After all."], native: ["I knew it!", "Sure enough.", "Just as I expected."] },
        { ja: "まあまあ", en: ["So-so.", "Not bad."], native: ["It's decent.", "Can't complain.", "It's alright, I guess."] },
        { ja: "なんとなく", en: ["Somehow.", "For no reason."], native: ["Just because.", "I can't put my finger on it.", "No particular reason."] },
        { ja: "せっかく", en: ["Since we have the chance.", "It would be a waste not to."], native: ["We might as well.", "It'd be a shame not to.", "Since we're already here."] },
        { ja: "さすが", en: ["As expected.", "That's impressive."], native: ["You never disappoint!", "That's so like you!", "Leave it to you!"] },
    ],
    "毎日する活動・動作": [
        { ja: "起きる", en: ["I wake up.", "I get up."], native: ["I roll out of bed.", "I'm up.", "I drag myself out of bed."] },
        { ja: "準備する", en: ["I prepare.", "I get ready."], native: ["I get myself together.", "I freshen up.", "I gear up."] },
        { ja: "出かける", en: ["I go out.", "I leave."], native: ["I head out.", "I'm off.", "I hit the road."] },
        { ja: "休憩する", en: ["I take a break.", "I rest."], native: ["I take five.", "I chill for a bit.", "I recharge."] },
        { ja: "片付ける", en: ["I clean up.", "I tidy up."], native: ["I straighten things up.", "I declutter.", "I put things away."] },
        { ja: "寝る", en: ["I go to bed.", "I sleep."], native: ["I hit the sack.", "I crash.", "I call it a night."] },
        { ja: "食べる", en: ["I eat.", "I have a meal."], native: ["I grab a bite.", "I dig in.", "I chow down."] },
        { ja: "サボる", en: ["I skip.", "I don't go."], native: ["I play hooky.", "I blow it off.", "I slack off."] },
    ],
    "移動に関する表現": [
        { ja: "向かう", en: ["I go to ~.", "I'm going to ~."], native: ["I'm heading to ~.", "I'm on my way to ~.", "I'm making my way to ~."] },
        { ja: "着く", en: ["I arrive.", "I get there."], native: ["I'm here.", "I just pulled up.", "I made it."] },
        { ja: "戻る", en: ["I go back.", "I return."], native: ["I head back.", "I swing back.", "I make my way back."] },
        { ja: "寄る", en: ["I stop by.", "I visit."], native: ["I swing by.", "I pop in.", "I drop by."] },
        { ja: "急ぐ", en: ["I hurry.", "I rush."], native: ["I hustle.", "I pick up the pace.", "I book it."] },
        { ja: "迷う", en: ["I'm lost.", "I can't find the way."], native: ["I'm all turned around.", "I took a wrong turn.", "I'm going in circles."] },
        { ja: "間に合う", en: ["I'm on time.", "I make it."], native: ["I made it just in time.", "I caught it.", "I barely made it."] },
        { ja: "遅れる", en: ["I'm late.", "I'm delayed."], native: ["I'm running late.", "I'm behind schedule.", "I got held up."] },
    ],
    "人とかかわる活動": [
        { ja: "誘う", en: ["I invite.", "I ask someone to come."], native: ["I hit someone up.", "I ask someone to tag along.", "I loop someone in."] },
        { ja: "断る", en: ["I refuse.", "I say no."], native: ["I pass.", "I take a rain check.", "I'll have to sit this one out."] },
        { ja: "手伝う", en: ["I help.", "I assist."], native: ["I give a hand.", "I pitch in.", "I've got your back."] },
        { ja: "相談する", en: ["I consult.", "I talk about it."], native: ["I run it by someone.", "I pick someone's brain.", "I bounce ideas off someone."] },
        { ja: "謝る", en: ["I apologize.", "I say sorry."], native: ["My bad.", "I owe you an apology.", "I messed up, sorry."] },
        { ja: "褒める", en: ["I praise.", "I compliment."], native: ["I give props.", "I hype someone up.", "I give someone a shoutout."] },
        { ja: "約束する", en: ["I promise.", "I make a plan."], native: ["I give my word.", "It's a deal.", "You have my word."] },
        { ja: "紹介する", en: ["I introduce.", "I present."], native: ["Let me put you in touch.", "You've gotta meet ~.", "I'll hook you up with ~."] },
    ],
    "感想を伝える": [
        { ja: "すごい", en: ["It's amazing.", "It's great."], native: ["That's insane!", "No way!", "That's next level!"] },
        { ja: "おもしろい", en: ["It's interesting.", "It's funny."], native: ["That's hilarious!", "That cracked me up!", "That's a good one!"] },
        { ja: "ヤバい", en: ["It's crazy.", "It's unbelievable."], native: ["That's wild!", "No joke!", "That's nuts!"] },
        { ja: "まじで？", en: ["Really?", "Seriously?"], native: ["For real?", "Are you kidding me?", "No way!"] },
        { ja: "ありえない", en: ["That's impossible.", "I can't believe it."], native: ["That's unreal.", "Get out of here!", "You've gotta be kidding."] },
        { ja: "懐かしい", en: ["I miss it.", "It brings back memories."], native: ["That takes me back.", "The good old days.", "What a throwback."] },
        { ja: "うらやましい", en: ["I'm jealous.", "I envy you."], native: ["I'm so jelly!", "Lucky you!", "I wish that were me."] },
        { ja: "もったいない", en: ["It's a waste.", "That's wasteful."], native: ["What a shame.", "That's such a waste.", "Don't let it go to waste."] },
    ],
    "どのくらいかを表現する": [
        { ja: "すごく", en: ["Very.", "Very much."], native: ["Super.", "Crazy ~.", "Insanely ~."] },
        { ja: "ちょっと", en: ["A little.", "A bit."], native: ["Slightly.", "Kind of.", "Just a tad."] },
        { ja: "けっこう", en: ["Quite.", "Pretty much."], native: ["Pretty ~.", "Fairly ~.", "I'd say it's quite ~."] },
        { ja: "全然", en: ["Not at all.", "Not even close."], native: ["Not one bit.", "Not in the slightest.", "Nope, not even."] },
        { ja: "ほとんど", en: ["Almost.", "Nearly."], native: ["Pretty much.", "Just about.", "More or less."] },
        { ja: "めっちゃ", en: ["Very.", "Really."], native: ["So ~.", "Ridiculously ~.", "Hella ~."] },
        { ja: "まあまあ", en: ["So-so.", "Not bad."], native: ["It's decent.", "It's okay-ish.", "Can't complain."] },
        { ja: "たくさん", en: ["A lot.", "Many."], native: ["Tons of.", "A bunch of.", "Loads of."] },
    ],
};
