const VOCAB_DATA = {
    "天気・季節": [
        { ja: "明日は雨だと思う", en: ["I think it will rain tomorrow."], native: ["I bet it's gonna rain tomorrow.", "Looks like rain tomorrow."] },
        { ja: "今日めっちゃ暑くない？", en: ["Isn't it really hot today?"], native: ["It's boiling out here!", "It's crazy hot today, right?"] },
        { ja: "最近やっと涼しくなってきた", en: ["It's finally getting cooler recently."], native: ["It's finally cooling down.", "We're finally getting some relief from the heat."] },
        { ja: "朝寒すぎて布団から出たくない", en: ["It's too cold in the morning to get out of bed."], native: ["It's so cold I can't drag myself out of bed.", "I just wanna stay under the covers."] },
        { ja: "桜もう咲いたかな", en: ["I wonder if the cherry blossoms have bloomed yet."], native: ["Are the cherry blossoms out yet?", "Have the cherry blossoms started blooming?"] },
        { ja: "台風来るらしいよ", en: ["I heard a typhoon is coming."], native: ["Apparently there's a typhoon heading our way.", "They say a typhoon's coming."] },
        { ja: "洗濯物外に干しちゃった", en: ["I left the laundry hanging outside."], native: ["I totally left my laundry out.", "Oh no, my laundry's still outside."] },
        { ja: "傘持ってくればよかった", en: ["I should have brought an umbrella."], native: ["I wish I'd grabbed an umbrella.", "I knew I should've brought an umbrella."] },
    ],
    "仕事・学校": [
        { ja: "今日の会議だるいな", en: ["I don't want to go to today's meeting."], native: ["Ugh, I'm so not feeling today's meeting.", "I'm dreading today's meeting."] },
        { ja: "締め切りやばい、間に合わないかも", en: ["The deadline is tight. I might not make it."], native: ["The deadline's killing me. I don't think I'm gonna make it.", "I'm cutting it super close with this deadline."] },
        { ja: "上司に褒められた", en: ["My boss praised me.", "My boss complimented me."], native: ["My boss gave me a shoutout.", "I got props from my boss."] },
        { ja: "残業したくないのに", en: ["I don't want to work overtime."], native: ["I really don't wanna stay late.", "The last thing I need is overtime."] },
        { ja: "明日テストなのに全然勉強してない", en: ["I have a test tomorrow but I haven't studied at all."], native: ["I've got a test tomorrow and I haven't cracked a book.", "My test is tomorrow and I'm totally unprepared."] },
        { ja: "有給取りたいけど言いにくい", en: ["I want to take a day off but it's hard to ask."], native: ["I wanna use my PTO but I feel weird asking.", "I need a day off but I don't know how to bring it up."] },
        { ja: "通勤時間もったいないよね", en: ["Commuting time is such a waste, isn't it?"], native: ["The commute is such a waste of time.", "I feel like I'm throwing away hours on my commute."] },
        { ja: "今日はやる気が出ない", en: ["I'm not motivated today."], native: ["I'm just not feeling it today.", "I've got zero motivation today."] },
    ],
    "食事・料理": [
        { ja: "昨日の夜何食べた？", en: ["What did you eat last night?"], native: ["What'd you have for dinner last night?", "What did you end up eating last night?"] },
        { ja: "お腹すいた、何か食べに行こう", en: ["I'm hungry. Let's go eat something."], native: ["I'm starving. Let's grab something to eat.", "I could eat. Wanna go get some food?"] },
        { ja: "この店のラーメンめっちゃうまい", en: ["The ramen at this place is really good."], native: ["This place has killer ramen.", "Dude, the ramen here is insane."] },
        { ja: "自炊した方がいいのは分かってる", en: ["I know I should cook at home more."], native: ["I know I should be cooking more.", "I really need to start cooking for myself."] },
        { ja: "コンビニ弁当ばっかりで飽きた", en: ["I'm tired of eating convenience store lunches."], native: ["I'm so over convenience store meals.", "I'm sick of grabbing lunch at the konbini."] },
        { ja: "この前行ったカフェすごくよかった", en: ["The cafe I went to the other day was really nice."], native: ["I checked out this cafe the other day and it was amazing.", "I found this awesome cafe recently."] },
        { ja: "食べすぎてお腹やばい", en: ["I ate too much and my stomach hurts."], native: ["I'm so stuffed I can barely move.", "I totally overdid it. My stomach's about to explode."] },
        { ja: "辛いの好き？", en: ["Do you like spicy food?"], native: ["Are you into spicy stuff?", "Can you handle spicy food?"] },
    ],
    "趣味・エンタメ": [
        { ja: "昨日見た映画感動したよ", en: ["The movie I saw yesterday was moving."], native: ["That movie I watched yesterday hit me right in the feels.", "I saw this movie yesterday and it got me so emotional."] },
        { ja: "最近ハマってるドラマある？", en: ["Is there a drama you're into recently?"], native: ["Are you binge-watching anything right now?", "Got any show recommendations?"] },
        { ja: "この曲聴いてみて、めっちゃいいから", en: ["Listen to this song. It's really good."], native: ["You gotta hear this song. It's a banger.", "Check this song out. It slaps."] },
        { ja: "ゲームしすぎて寝不足", en: ["I played games too much and didn't get enough sleep."], native: ["I was up way too late gaming.", "I gamed till like 3 AM and I'm running on fumes."] },
        { ja: "週末どこか行きたいな", en: ["I want to go somewhere this weekend."], native: ["I feel like getting out this weekend.", "I wanna do something fun this weekend."] },
        { ja: "その漫画、最新刊読んだ？", en: ["Did you read the latest volume of that manga?"], native: ["Have you read the newest volume yet?", "Did you catch the latest chapter?"] },
        { ja: "カラオケ久しぶりに行きたい", en: ["I want to go to karaoke for the first time in a while."], native: ["I'm dying to go to karaoke. It's been forever.", "We should totally hit up karaoke soon."] },
        { ja: "推しが最高すぎる", en: ["My favorite idol is the best."], native: ["My fave is just on another level.", "I'm obsessed with my bias right now."] },
    ],
    "友達・誘い": [
        { ja: "今度の土曜ヒマ？", en: ["Are you free this Saturday?"], native: ["You got anything going on this Saturday?", "What are you up to this Saturday?"] },
        { ja: "久しぶりに飲みに行かない？", en: ["Do you want to go drinking after a long time?"], native: ["We should grab drinks soon. It's been a minute.", "Wanna go out for drinks? It's been ages."] },
        { ja: "ごめん、その日はちょっと無理", en: ["Sorry, I can't on that day."], native: ["Sorry, that day doesn't work for me.", "Ah man, I can't make it that day."] },
        { ja: "もうちょっと早く言ってよ", en: ["You should have told me sooner."], native: ["A little more heads-up would've been nice.", "Why didn't you tell me earlier?"] },
        { ja: "あいつ最近連絡ないよね", en: ["We haven't heard from him/her recently."], native: ["Have you heard from them lately? They've been MIA.", "They've been totally off the grid recently."] },
        { ja: "集合場所どこにする？", en: ["Where should we meet?"], native: ["Where are we meeting up?", "What's the meeting spot?"] },
        { ja: "遅れそう、先に始めてて", en: ["I might be late. Please start without me."], native: ["I'm running late. Go ahead and start without me.", "I'm gonna be a bit late. Don't wait up."] },
        { ja: "今日楽しかったね、また遊ぼう", en: ["Today was fun. Let's hang out again."], native: ["That was a blast. We should do this again.", "I had so much fun. Let's link up again soon."] },
    ],
    "買い物・お金": [
        { ja: "これセールで安くなってる", en: ["This is on sale and cheaper."], native: ["This is marked down. What a deal!", "Oh nice, this is on sale."] },
        { ja: "欲しいけど高すぎる", en: ["I want it but it's too expensive."], native: ["I want it so bad but it's way out of my budget.", "It's tempting but I can't justify the price."] },
        { ja: "ネットで買った方が安いかも", en: ["It might be cheaper to buy it online."], native: ["I bet it's cheaper online.", "Let me check if I can get a better deal online."] },
        { ja: "今月お金使いすぎた", en: ["I spent too much money this month."], native: ["I totally blew my budget this month.", "I went way overboard with spending this month."] },
        { ja: "これどこで買ったの？", en: ["Where did you buy this?"], native: ["Where'd you get this?", "Ooh, where's this from?"] },
        { ja: "ポイントカード持ってますか？", en: ["Do you have a points card?"], native: ["Got a rewards card?", "Do you have a loyalty card?"] },
        { ja: "サイズ合わなかったから返品したい", en: ["The size didn't fit, so I want to return it."], native: ["It didn't fit so I need to return it.", "I gotta take this back. Wrong size."] },
        { ja: "給料日まであと少し", en: ["Payday is just around the corner."], native: ["Just gotta make it to payday.", "I'm counting down the days till payday."] },
    ],
    "体調・健康": [
        { ja: "ちょっと風邪っぽい", en: ["I think I might have a cold."], native: ["I feel like I'm coming down with something.", "I think I'm getting sick."] },
        { ja: "昨日寝れなくてしんどい", en: ["I couldn't sleep last night and I'm exhausted."], native: ["I barely slept last night and I'm wrecked.", "I tossed and turned all night. I'm dead."] },
        { ja: "最近運動不足だなぁ", en: ["I haven't been exercising enough lately."], native: ["I've been so lazy about working out.", "I really need to get back in shape."] },
        { ja: "肩こりやばい、マッサージ行きたい", en: ["My shoulders are so stiff. I want to get a massage."], native: ["My shoulders are killing me. I need a massage.", "I'm so tense. I could really use a massage."] },
        { ja: "花粉症つらい", en: ["My hay fever is bad."], native: ["Allergies are destroying me right now.", "Pollen season is no joke."] },
        { ja: "早く寝ないとまた寝坊する", en: ["I need to go to bed early or I'll oversleep again."], native: ["If I don't hit the sack soon, I'm totally sleeping through my alarm.", "I gotta crash early or I'll oversleep again."] },
        { ja: "目が疲れてきた", en: ["My eyes are getting tired."], native: ["My eyes are starting to strain.", "I've been staring at screens too long."] },
        { ja: "コーヒー飲まないと頭動かない", en: ["I can't think without coffee."], native: ["I'm useless without my coffee.", "I need caffeine to function."] },
    ],
    "気持ち・リアクション": [
        { ja: "まじで？信じられない", en: ["Really? I can't believe it."], native: ["No way! Are you serious?", "Shut up! For real?"] },
        { ja: "やっぱりそうだと思った", en: ["I knew it. I thought so."], native: ["I knew it! Called it.", "I had a feeling. Just as I thought."] },
        { ja: "それちょっとうらやましい", en: ["I'm a little jealous of that."], native: ["Okay, I'm lowkey jealous.", "Lucky you. I wish that were me."] },
        { ja: "なんかモヤモヤする", en: ["Something is bothering me."], native: ["I can't shake this weird feeling.", "Something just doesn't sit right."] },
        { ja: "あー言わなきゃよかった", en: ["I wish I hadn't said that."], native: ["Ugh, I should've kept my mouth shut.", "I totally put my foot in my mouth."] },
        { ja: "めっちゃ助かった、ありがとう", en: ["That was a big help. Thank you."], native: ["You're a lifesaver. Thanks so much.", "Seriously, thank you. You saved me."] },
        { ja: "もう無理、限界", en: ["I can't anymore. I'm at my limit."], native: ["I'm done. I've hit my limit.", "I literally cannot. I'm so over it."] },
        { ja: "考えすぎかもしれないけど気になる", en: ["I might be overthinking it, but it bothers me."], native: ["I'm probably reading too much into it, but it bugs me.", "Maybe I'm overthinking this, but I can't let it go."] },
    ],
};
